name: QSAR
channels:
  - anaconda
  - conda-forge
  - schrodinger
  - ambermd
  - omnia
  - defaults
dependencies:
  - click
  - openbabel
  - rdkit
  - numpy=1.18.5
  - pandas
  - ambertools=20
  - openmm

