name: qsarpackage
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - click
  - numpy
  - pandas
  - scipy
  - openbabel
  - rdkit
  - openmm
  - openmmforcefields
  - acpype
