name: qsarpackage
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - click
  - openbabel
  - rdkit
  - numpy
  - pandas
  - ambertools=22.*
  - openmm
  - openmmforcefields
  - acpype
  - hatchling
  - scipy
