name: qsarpackage
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - click
  - numpy
  - pandas
  - scipy
  - openbabel
  - rdkit
  - openmm
  - openmmforcefields
  - anaconda-client
  - conda-build
  - conda-verify
