name: publish_conda
 
on:
  release:
    types: [released]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: hellmrf/conda-publish-action@dev
      with:
        anacondatoken: ${{ secrets.CONDA_HELITONMRF_TOKEN }}
        platforms: 'osx linux'
        additional_params: -c conda-forge --label dev
